# Generated by Django 5.2.17 on 2026-09-22 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0004_grupos_e_senhas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Opcional. A imagem enviada tem prioridade sobre o endereço externo.', upload_to='produtos/%Y/%m/', verbose_name='Imagem enviada'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_externa',
            field=models.URLField(blank=True, help_text='Opcional. Informe um endereço completo com http:// ou https://.', max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='URL da imagem'),
        ),
    ]
